# Generated by Django 5.2.12 on 2026-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_liveclass_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveclass',
            old_name='zoom_link',
            new_name='meet_link',
        ),
        migrations.AddField(
            model_name='liveclass',
            name='whiteboard_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
