# Generated by Django 5.2.12 on 2026-03-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_quiz_question_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ai_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
