# Generated by Django 5.2.12 on 2026-04-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_submission_feedback_submission_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='feedback',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='grade',
        ),
        migrations.AddField(
            model_name='submission',
            name='checked_file',
            field=models.FileField(blank=True, null=True, upload_to='checked/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
            preserve_default=False,
        ),
    ]
