# Generated by Django 5.2.12 on 2026-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_handout'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
