# Generated by Django 5.2.12 on 2026-04-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
