# Generated by Django 5.2.12 on 2026-04-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_callanswer_rename_is_active_liveclass_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
