# Generated by Django 5.2.12 on 2026-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_icecandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
    ]
