# Generated by Django 5.2.12 on 2026-04-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_liveclass_recording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='recording',
        ),
    ]
