# Generated by Django 5.2.12 on 2026-05-01 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_message_live_class_message_timestamp_chatfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='live_class',
        ),
        migrations.AddField(
            model_name='attendance',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='room',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
