# Generated by Django 5.2.12 on 2026-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_student_attendance_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='teacher_started',
            field=models.BooleanField(default=False),
        ),
    ]
