# Generated by Django 5.2.12 on 2026-06-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_liveclass_teacher_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='room',
        ),
        migrations.AddField(
            model_name='attendance',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.liveclass'),
        ),
        migrations.AlterField(
            model_name='message',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.liveclass'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.liveclass'),
        ),
    ]
