# Generated by Django 5.2.12 on 2026-06-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_user_attendance_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.liveclass'),
        ),
        migrations.AlterField(
            model_name='message',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.liveclass'),
        ),
    ]
