# Generated by Django 5.2.12 on 2026-06-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_user_attendance_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
