# Generated by Django 5.2.12 on 2026-06-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_attendance_live_class_alter_message_live_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.liveclass'),
        ),
    ]
