# Generated by Django 5.2.12 on 2026-07-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recording',
            name='live_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.liveclass'),
        ),
    ]
