# Generated by Django 5.2.12 on 2026-07-23 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_recording_description_recording_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('checked', 'Checked')], default='submitted', max_length=20),
        ),
    ]
