# Generated by Django 5.2.12 on 2026-08-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_submission_assignment_alter_submission_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
