# Generated by Django 5.2.12 on 2026-08-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='badges',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='core.achievement'),
        ),
    ]
