# Generated by Django 5.2.12 on 2026-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_studentanswer_quiz_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doubts/'),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
