# Generated by Django 5.2.12 on 2026-08-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_doubt_image_alter_doubt_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
