# Generated by Django 5.2.12 on 2026-08-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_doubt_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='doubt_answers/'),
        ),
    ]
