# Generated by Django 5.2.12 on 2026-09-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_refund_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_event_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processed', 'Processed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core.paymenttransaction')),
            ],
        ),
    ]
