# Generated by Django 5.2.12 on 2026-09-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='checked_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='checked/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(max_length=255, upload_to='submissions/'),
        ),
    ]
