# Generated by Django 5.2.12 on 2026-09-17 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_submission_checked_file_alter_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.module'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='video_solution_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.module'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.course'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('module__isnull', True)), models.Q(('lesson__isnull', True), ('module__isnull', False)), _connector='OR'), name='assignment_exactly_one_parent'),
        ),
    ]
