# Generated by Django 5.2.12 on 2026-09-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_videolecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_handouts', to='core.module'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
        ),
        migrations.AddConstraint(
            model_name='handout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('module__isnull', True)), models.Q(('lesson__isnull', True), ('module__isnull', False)), _connector='OR'), name='handout_exactly_one_parent'),
        ),
    ]
