# Generated by Django 5.2.12 on 2026-09-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_handout_module_alter_handout_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='learning_recordings/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_recordings', to='core.lesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_recordings', to='core.module')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('module__isnull', True)), models.Q(('lesson__isnull', True), ('module__isnull', False)), _connector='OR'), name='learning_recording_exactly_one_parent')],
            },
        ),
    ]
