# Generated by Django 5.2.12 on 2026-09-29 08:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_learningrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecording',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='learning_recordings/'),
        ),
    ]
